<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Deals</name>
   <tag></tag>
   <elementGuidId>1ce993ab-98cf-42d2-91e3-c69c57b011da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.page-heading.text-brand</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='content']/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>9383c83a-355f-4f24-a63c-d539ac0b848a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-heading text-brand</value>
      <webElementGuid>82d909dd-7e38-4cc1-867e-ddabfb869a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Deals</value>
      <webElementGuid>66004f1a-9b70-4796-8ec4-5676712936f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;container&quot;]/h1[@class=&quot;page-heading text-brand&quot;]</value>
      <webElementGuid>b0031f0c-647a-41f0-af9b-4c0fefdae4f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content']/div/h1</value>
      <webElementGuid>e7467585-0ad9-4a9e-918c-e15bbfdccb66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deals'])[3]/following::h1[1]</value>
      <webElementGuid>6baa5596-7bba-495d-a5ce-1102eb419f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop By'])[2]/following::h1[1]</value>
      <webElementGuid>8f05220f-668d-43b8-957f-b05e03b78101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Narrow your search'])[1]/preceding::h1[1]</value>
      <webElementGuid>12eaa995-dfb3-4c5d-ae5d-4d107cb7df69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color'])[1]/preceding::h1[1]</value>
      <webElementGuid>791ba8ce-562f-461a-a9cb-dd2a9ec3cc60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>da12dc3c-d14e-420e-ad6a-d1099beb0f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Deals' or . = 'Deals')]</value>
      <webElementGuid>a7fcf389-d66e-4379-af17-2c24a2a36fcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
