<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Closeout_card-img-top</name>
   <tag></tag>
   <elementGuidId>53d9f932-049d-4ff8-9cdf-00fc211fd882</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.card-img-top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nxt-content']/div/div[2]/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>058f298b-8a4d-4463-8060-b2a28450b48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://imgsirv.geiger.com/master/122009/web/122009_1.jpg?thumbnail=275</value>
      <webElementGuid>2c9864e8-94b0-4091-a52e-8ec446fd0d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Rugby Stripe Scarf</value>
      <webElementGuid>58c46a3f-af78-4527-811b-19da504829b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-top</value>
      <webElementGuid>cdbcca53-4814-4750-8b9b-28914769834c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>983d7471-1197-4f4d-8d00-268edef9aa3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nxt-content&quot;)/div[@class=&quot;results-container&quot;]/div[@class=&quot;card-deck card-deck-wrap card-deck-wrap-2 card-deck-wrap-lg-3 card-deck-wrap-xl-4 card-deck-wrap-2x-5 justify-content-start&quot;]/div[@class=&quot;card product-card mb-4&quot;]/div[@class=&quot;img-responsive-pad&quot;]/a[1]/img[@class=&quot;card-img-top&quot;]</value>
      <webElementGuid>f276d3bc-a96c-4431-80b8-2b1e6f6e8e63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nxt-content']/div/div[2]/div/div/a/img</value>
      <webElementGuid>f2afd0d0-689c-423d-8ca0-27f8a5de7860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Rugby Stripe Scarf']</value>
      <webElementGuid>b89a5941-f5e0-492f-b881-95d28464b457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/a/img</value>
      <webElementGuid>c65e21d1-d74e-400d-9276-8a7d02331f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://imgsirv.geiger.com/master/122009/web/122009_1.jpg?thumbnail=275' and @alt = 'Rugby Stripe Scarf']</value>
      <webElementGuid>62d2dfcf-be48-4749-b8b2-48de3b4601ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
