<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_(Current Page)_card-img-top</name>
   <tag></tag>
   <elementGuidId>b1617ffd-3fcd-4225-9fdd-c7f299d83cd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.card-img-top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nxt-content']/div/div[2]/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>06f36c67-11c9-4940-89a9-bf23bb5f02fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://imgsirv.geiger.com/master/111117/web/111117_1.jpg?thumbnail=275</value>
      <webElementGuid>575c6e93-d252-45f6-b61a-83cda9ee1321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Crosswind Quarter Zip</value>
      <webElementGuid>7c6897c4-064a-4f5a-a2ee-3366401befc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img-top</value>
      <webElementGuid>f8ca38ca-3631-40dc-86aa-cda04be478bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>d0b693a1-14a9-4571-a5b9-ac64082689c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nxt-content&quot;)/div[@class=&quot;results-container&quot;]/div[@class=&quot;card-deck card-deck-wrap card-deck-wrap-2 card-deck-wrap-lg-3 card-deck-wrap-xl-4 card-deck-wrap-2x-5 justify-content-start&quot;]/div[@class=&quot;card product-card mb-4&quot;]/div[@class=&quot;img-responsive-pad&quot;]/a[1]/img[@class=&quot;card-img-top&quot;]</value>
      <webElementGuid>43fa80f9-03e3-41e8-a068-4f1d32d4d75e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nxt-content']/div/div[2]/div/div/a/img</value>
      <webElementGuid>fec786e9-e670-475f-92a7-d952904bf878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Crosswind Quarter Zip']</value>
      <webElementGuid>a1fc23b0-f87c-4b33-8a11-52bc484c7ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/a/img</value>
      <webElementGuid>7a699ae6-c879-4359-b0c7-5dc32f109ee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://imgsirv.geiger.com/master/111117/web/111117_1.jpg?thumbnail=275' and @alt = 'Crosswind Quarter Zip']</value>
      <webElementGuid>5d709bc3-c9ad-47d0-b835-ee2d4e8ff0d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
