<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Footwear</name>
   <tag></tag>
   <elementGuidId>9155a7b9-9523-4a3f-afd1-4a2d6316ac91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.page-heading.text-brand</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='content']/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>571b6133-52d8-44a7-a02c-5e871aa3828d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-heading text-brand</value>
      <webElementGuid>e5bf6611-a5e4-4820-9418-51d472fe81e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Footwear</value>
      <webElementGuid>719e643f-2d53-4183-82fb-fff159f44471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;container&quot;]/h1[@class=&quot;page-heading text-brand&quot;]</value>
      <webElementGuid>bad5dc87-10ff-43fb-9fee-c4408b64fa75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content']/div/h1</value>
      <webElementGuid>acdcf7fe-0eec-42c7-834c-cda22e7ebb72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Footwear'])[2]/following::h1[1]</value>
      <webElementGuid>cf11e3af-9e7c-4d12-8518-44dc3d730b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessories'])[2]/following::h1[1]</value>
      <webElementGuid>720efffb-7fba-43fa-9a2d-3ccd1d4c0312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Narrow your search'])[1]/preceding::h1[1]</value>
      <webElementGuid>ece4c3d9-74b8-47af-baa3-f855eeb03139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color'])[1]/preceding::h1[1]</value>
      <webElementGuid>03765d3b-05e3-4a36-badb-df7561a99dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>e87235ec-9c05-4aae-b5d6-ef2e99bea41c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Footwear' or . = 'Footwear')]</value>
      <webElementGuid>affebfed-70a2-45b8-88e0-e6a14c619b39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
