<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_XSM</name>
   <tag></tag>
   <elementGuidId>070868fa-0cae-46c1-8d9f-5591068df82f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.btn-group > button.btn.btn-outline-secondary.btn-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@value='320974']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>90d47fe8-7123-446f-bd80-d3b247bc0c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>04386906-c8dd-49e5-818e-3b7d7efe125f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>320974</value>
      <webElementGuid>20e6ed75-023d-4ef0-a292-63d16026ef14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-outline-secondary btn-sm</value>
      <webElementGuid>aec89c2d-ea4a-4f2a-85ca-a78194cc8681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> XSM </value>
      <webElementGuid>c64ac0c6-39f7-4ab7-a3fe-e61264f5fefc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customizer&quot;)/div[@class=&quot;card-body&quot;]/div[@class=&quot;customizer-step customize-quantity customize-sizes mb-3&quot;]/div[@class=&quot;btn-toolbar mb-2&quot;]/div[@class=&quot;btn-group&quot;]/button[@class=&quot;btn btn-outline-secondary btn-sm&quot;]</value>
      <webElementGuid>5a28a986-7a12-48cf-8d02-1c8d55fac5ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@value='320974']</value>
      <webElementGuid>3002fbff-f3f5-4d43-b53f-cc6e057e4166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customizer']/div/div[3]/div[7]/div/button</value>
      <webElementGuid>77e109c3-02cb-456f-a58e-27a0a94f1429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The minimum quantity for this product is 12.'])[1]/following::button[1]</value>
      <webElementGuid>26ec1b62-d0c6-49cb-9dc5-fcbb4b606016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='total'])[1]/following::button[1]</value>
      <webElementGuid>89b70f07-317c-4f6a-965b-ee2c5e88ae0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ea'])[5]/preceding::button[1]</value>
      <webElementGuid>fdab83cb-87a9-455c-9280-52740ea465b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='XSM']/parent::*</value>
      <webElementGuid>372dc2e6-bc81-4913-bb25-dbef9f6c7758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/button</value>
      <webElementGuid>285bb0b5-c1b1-4afb-89d3-0fb340cb4529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' XSM ' or . = ' XSM ')]</value>
      <webElementGuid>6cd81325-2fa3-4992-9e80-4d06bacc02da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
