<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SML_sizes320972</name>
   <tag></tag>
   <elementGuidId>2b016f15-d43b-48c7-a7c4-c289e1645f7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product-size-320972</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product-size-320972']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0b9ecc8-827c-4571-90b4-f06918683671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0afe8f55-4629-4275-8b44-b57225d90db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e3b2ae86-dddf-4231-8f8b-c9c638f24f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product-size-320972</value>
      <webElementGuid>9b4a6586-948b-44d3-8a57-a4a58fda87c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sizes[320972]</value>
      <webElementGuid>993b65f2-8e58-446f-b66a-62d2f02d4039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>2feb86c5-a03a-4119-99fd-226f5553ae22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>efa4c2b4-96ae-43ba-a3ef-beb9daae8b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>487bbd49-77b3-4aec-9dd9-36685468d2d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-size-320972&quot;)</value>
      <webElementGuid>57cba807-c4bc-4a9d-a8e9-5704a0644e57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product-size-320972']</value>
      <webElementGuid>65c96c73-b761-4b37-963e-78280f5f915b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customizer']/div/div[3]/div[2]/div/div/div/input</value>
      <webElementGuid>25ecc8a2-6100-499d-bb80-ffa3b86e1916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/input</value>
      <webElementGuid>dfa33c45-92c8-418c-be40-e03d89f95a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'product-size-320972' and @name = 'sizes[320972]' and @type = 'number']</value>
      <webElementGuid>e41f3cb3-5133-4d73-a5e0-31f685600198</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
