<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_XLG_sizes320973</name>
   <tag></tag>
   <elementGuidId>366223f3-2335-4251-9167-d1b411cdbe4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product-size-320973</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='product-size-320973']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8da7fb9f-3f3e-4b35-b344-7fccfc6965c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>225b0ec7-f166-4019-8210-5640dab75f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7516c4bc-589b-4bd6-8f67-17b01f776daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product-size-320973</value>
      <webElementGuid>d7312f72-2020-4271-b026-bfe114d32e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sizes[320973]</value>
      <webElementGuid>16b13d66-a1e1-4d20-abc3-9aca023b9158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>1a59d87d-eadc-48c5-a5c0-4926c413012b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>794040bb-cfb0-4fa9-aa79-6df2399abcd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ea652e45-9d38-40b4-9558-654c64c5b310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-size-320973&quot;)</value>
      <webElementGuid>5aca5d1d-da1d-49f4-89ca-439e6970da88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='product-size-320973']</value>
      <webElementGuid>b7c73a3f-5437-4b96-8e89-0956549b087d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customizer']/div/div[3]/div[6]/div/div/div/input</value>
      <webElementGuid>77925a2a-0f32-41c6-897a-3ed5818eab33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/input</value>
      <webElementGuid>b7b3bc57-99b4-4f8b-b1f4-f9d1c2bae4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'product-size-320973' and @name = 'sizes[320973]' and @type = 'number']</value>
      <webElementGuid>439e870e-4be2-41e9-b9a1-c861eb20cb33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
