<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Corporate Gift Services Kitting Drop Shi_2877e9</name>
   <tag></tag>
   <elementGuidId>b405da59-f48f-43fd-9253-f76aa17eafd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/nav[2]/div/ol/li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.breadcrumb-item.active.d-none.d-sm-inline-block</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b1b15443-aea9-4144-ad32-cee4ea20e5e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>c473e4f2-2e39-47e5-a467-ee9abd527dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>breadcrumb-item active d-none d-sm-inline-block</value>
      <webElementGuid>79a10843-95f7-4a03-bdf8-907251aee25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Corporate Gift Services Kitting Drop Shipping and Personalization</value>
      <webElementGuid>86f0b018-66eb-4b6a-8b7b-8c81fd665bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/nav[@class=&quot;nav-breadcrumb&quot;]/div[@class=&quot;container&quot;]/ol[@class=&quot;breadcrumb&quot;]/li[@class=&quot;breadcrumb-item active d-none d-sm-inline-block&quot;]</value>
      <webElementGuid>f1f10502-1cb6-43df-a107-c9d14668dc0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/nav[2]/div/ol/li[2]</value>
      <webElementGuid>7fdf54a7-0482-4ca1-8e37-d8ffc99c833d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::li[1]</value>
      <webElementGuid>71d89341-d83a-482c-8c34-5ea72b898e9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shopping Cart'])[1]/following::li[2]</value>
      <webElementGuid>b0ac233d-52ff-48aa-9c33-b6347a5150cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special Gift Services: Kitting, Drop Shipping &amp; Personalization'])[1]/preceding::li[1]</value>
      <webElementGuid>8dd7b0d5-629c-4563-9866-757dfb9b05f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='published: April 21, 2021'])[1]/preceding::li[1]</value>
      <webElementGuid>0e9c51fc-e06f-4c15-b18d-3dadc8e64261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Corporate Gift Services Kitting Drop Shipping and Personalization']/parent::*</value>
      <webElementGuid>dd2d51cc-e495-412c-b2c3-1987c68a0cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li[2]</value>
      <webElementGuid>a0e6d752-ab8c-498c-b181-23d3cb80147d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Corporate Gift Services Kitting Drop Shipping and Personalization' or . = 'Corporate Gift Services Kitting Drop Shipping and Personalization')]</value>
      <webElementGuid>0399ec13-35f3-443c-accd-5b0ddbb576ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
