<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kitting</name>
   <tag></tag>
   <elementGuidId>facb8eb9-75e5-411e-aca1-551a2b0f83ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='primaryNavigation']/div/ul/li[7]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.dropdown-menu.show > li > a.dropdown-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4964bbe8-ef48-456d-89be-84ecaf85583a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://yourlogo.geiger.com/c/corporate-gift-services-kitting-drop-shipping-and-personalization</value>
      <webElementGuid>856cc9f0-6e99-4cec-aadf-ac7d16774d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>91eff9d2-435b-4d49-b1bd-0c44c89431c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kitting</value>
      <webElementGuid>9a4ce4e0-761b-498d-9615-7904f121a624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primaryNavigation&quot;)/div[@class=&quot;navbar-content&quot;]/ul[@class=&quot;navbar-nav&quot;]/li[@class=&quot;nav-item dropdown show&quot;]/ul[@class=&quot;dropdown-menu show&quot;]/li[1]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>919b6524-afe2-4e9c-b1f3-ae5f77e19a49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='primaryNavigation']/div/ul/li[7]/ul/li/a</value>
      <webElementGuid>58038b7d-acb2-4e7d-9fb8-a2c12c52d140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Kitting')]</value>
      <webElementGuid>6bbfa94e-83a2-455d-a4d4-273ca97eccd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Services'])[1]/following::a[1]</value>
      <webElementGuid>8d2da4b0-de8a-4550-97a4-d546df852cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop by Theme'])[1]/following::a[2]</value>
      <webElementGuid>a8c5460e-e536-44fa-bafa-77ab4979b2c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corporate Programs'])[1]/preceding::a[1]</value>
      <webElementGuid>b325a99a-5c19-4307-b8b5-9290575997bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Custom Products'])[1]/preceding::a[2]</value>
      <webElementGuid>fa9cee70-1112-465c-85e5-5ac902bde205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kitting']/parent::*</value>
      <webElementGuid>5c7b3388-e608-4097-8200-1bbd881aaf01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://yourlogo.geiger.com/c/corporate-gift-services-kitting-drop-shipping-and-personalization')]</value>
      <webElementGuid>f1d435a8-7653-48d6-a608-cc6de7f7caa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/ul/li/a</value>
      <webElementGuid>61356d6a-0e9e-4db0-a6c7-bc2924b855f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://yourlogo.geiger.com/c/corporate-gift-services-kitting-drop-shipping-and-personalization' and (text() = 'Kitting' or . = 'Kitting')]</value>
      <webElementGuid>136d5b1f-4f51-4cbf-951c-39d7e8a2643b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
