<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Thermometers</name>
   <tag></tag>
   <elementGuidId>d1ccb4cf-3db2-4f9e-a9a8-af39107027e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.dropdown-menu.flyout-menu.show > li:nth-of-type(12) > a.dropdown-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='primaryNavigation']/div/ul/li/ul/li[4]/ul/li[12]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b0814da0-c763-459c-8ee2-53af83015470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://yourlogo.geiger.com/b/thermometers</value>
      <webElementGuid>835b5d41-0372-4ea4-946a-e1be630896a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>46c5825b-1511-44db-977f-e382234a5b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thermometers</value>
      <webElementGuid>f7e6a92a-d3fd-46e7-a3ae-2ac4c8c629ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primaryNavigation&quot;)/div[@class=&quot;navbar-content&quot;]/ul[@class=&quot;navbar-nav&quot;]/li[@class=&quot;nav-item dropdown show&quot;]/ul[@class=&quot;dropdown-menu show&quot;]/li[@class=&quot;flyout show&quot;]/ul[@class=&quot;dropdown-menu flyout-menu show&quot;]/li[12]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>5bb96985-dbef-4a56-87c9-c64da3634ae1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='primaryNavigation']/div/ul/li/ul/li[4]/ul/li[12]/a</value>
      <webElementGuid>0fa47e90-49fc-4b37-9a6b-46776c64fe52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Thermometers')]</value>
      <webElementGuid>743668f1-1cea-4cf7-bf95-d2598514c427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stress Relievers'])[1]/following::a[1]</value>
      <webElementGuid>8f0258ac-7f53-4b3f-8d20-e0f5457ee66b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Self-Care'])[1]/following::a[2]</value>
      <webElementGuid>21b54f9e-99f9-455d-a147-e9fda289d23e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tissue Packs'])[1]/preceding::a[1]</value>
      <webElementGuid>432f3abd-d81b-417d-8ae1-0dc1b8a900a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Health &amp; Wellness'])[1]/preceding::a[2]</value>
      <webElementGuid>230c62cd-183f-4a70-bc1e-78326b0c20e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thermometers']/parent::*</value>
      <webElementGuid>bff98a48-9868-4a4a-b091-f98af472eb2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://yourlogo.geiger.com/b/thermometers')]</value>
      <webElementGuid>2dceec41-162b-40f5-840c-20879bd9029b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[12]/a</value>
      <webElementGuid>759a348f-446b-4dc6-b7e6-a08358550f47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://yourlogo.geiger.com/b/thermometers' and (text() = 'Thermometers' or . = 'Thermometers')]</value>
      <webElementGuid>166126ae-a5f0-4845-9aa4-f7e451d33e73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
