<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Product Search_q</name>
   <tag></tag>
   <elementGuidId>4bd7dfc8-7750-44d7-bacc-1fdeab2ee7e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nxt-autocomplete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nxt-autocomplete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d92d7c1-da28-44ed-bad1-13a7eb19385d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>49b312fc-9d1d-4324-ae16-c17d9430ee69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nxt-autocomplete</value>
      <webElementGuid>5af1d6a7-759f-4d49-8e07-8d5e005a5b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>65cad13c-3633-49fc-a88e-a4c3623d81e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>160bd7c4-f6a0-4294-a9ad-9b97a0de4a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>What are you looking for?</value>
      <webElementGuid>7a0d5b32-52f3-4689-ac3c-bbdf5ffb811a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>dab50bdd-4f05-4111-b576-e24deaf29cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nxt-autocomplete&quot;)</value>
      <webElementGuid>9b7dcb02-2e8f-4936-8d4d-8488ef381577</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nxt-autocomplete']</value>
      <webElementGuid>4ed3ff64-7987-4248-8577-1d39be777d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[2]/form/input</value>
      <webElementGuid>a7f94333-0a68-4308-abc6-e2eb213b9a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3adbc21e-4d49-49a2-8736-ec2a06e01821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'nxt-autocomplete' and @name = 'q' and @placeholder = 'What are you looking for?']</value>
      <webElementGuid>12006f70-be1b-45ec-9b17-b302724afe1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
