<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nav_Home Custom Products</name>
   <tag></tag>
   <elementGuidId>c61935fa-bcc5-47e0-bd35-708f3f393f7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/nav[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>nav.nav-breadcrumb</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nav</value>
      <webElementGuid>1b2635d7-6652-4d99-8325-aa9eb33f563a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>breadcrumb</value>
      <webElementGuid>fb8fbfb6-72f9-4041-b6b4-af2bff314c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-breadcrumb</value>
      <webElementGuid>7f567712-2de5-4721-9f77-92124acc6d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home Custom Products</value>
      <webElementGuid>6d15b260-e14a-4194-a616-ac330c5b7505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/nav[@class=&quot;nav-breadcrumb&quot;]</value>
      <webElementGuid>b4805795-42ec-4a85-ad90-bd7e27ca73ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/nav[2]</value>
      <webElementGuid>388dee85-838d-4968-be7d-4b91e87da12a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shopping Cart'])[1]/following::nav[1]</value>
      <webElementGuid>7b532456-7876-4d16-87f9-fd94a5040e19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/following::nav[1]</value>
      <webElementGuid>049da623-02b2-485b-9a7f-fc304daffead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav[2]</value>
      <webElementGuid>043dd4b2-603c-4696-aee7-68a5927f59df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nav[(text() = 'Home Custom Products' or . = 'Home Custom Products')]</value>
      <webElementGuid>5deed3a6-4185-492d-bf89-21d536e00b80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
