<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Program Capabilities</name>
   <tag></tag>
   <elementGuidId>1105342e-2e06-49d5-b582-8dfeb8d14c79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/nav[2]/div/ol/li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.breadcrumb-item.active.d-none.d-sm-inline-block</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b7b5a2f7-c53c-4743-9548-5cd9635536ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>6af5445c-01e2-4d44-a1e3-96a287e5b236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>breadcrumb-item active d-none d-sm-inline-block</value>
      <webElementGuid>168792d1-97c4-4a3c-8a49-32399132b7f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Program Capabilities</value>
      <webElementGuid>e5d9a1e6-7732-45fd-be95-27ceb49147f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/nav[@class=&quot;nav-breadcrumb&quot;]/div[@class=&quot;container&quot;]/ol[@class=&quot;breadcrumb&quot;]/li[@class=&quot;breadcrumb-item active d-none d-sm-inline-block&quot;]</value>
      <webElementGuid>c8ca7106-d6f7-4ab7-81a5-c2e4f87e0639</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/nav[2]/div/ol/li[2]</value>
      <webElementGuid>4460d63c-75c9-49b3-97f6-5ab9ab0ce3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::li[1]</value>
      <webElementGuid>84bdea2d-55e3-42d5-a5b8-995513764ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shopping Cart'])[1]/following::li[2]</value>
      <webElementGuid>9b5eb0dc-aa90-4721-937b-daabec4c6eaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='World Class Technology and Award-Winning Ecommerce'])[1]/preceding::li[1]</value>
      <webElementGuid>97cf5ced-b869-4976-b22f-787f10926d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Program Capabilities']/parent::*</value>
      <webElementGuid>6ac1589e-1940-4085-947b-4571b042da31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li[2]</value>
      <webElementGuid>030bf151-ff0e-45bb-b58a-a714f758810f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Program Capabilities' or . = 'Program Capabilities')]</value>
      <webElementGuid>95719ac8-c112-49dd-b34b-4bc1cc2d2574</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
